# Generated by Django 3.0 on 2019-12-12 10:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191211_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'PYTHON'), ('Django', 'DJANGO'), ('Ui', 'UI'), ('RestApi', 'RESTAPI')], max_length=300)),
                ('trainers', multiselectfield.db.fields.MultiSelectField(choices=[('Sai', 'SAI'), ('Nani', 'NANI'), ('Satya', 'SATYA')], max_length=300)),
                ('branches', multiselectfield.db.fields.MultiSelectField(choices=[('Hyd', 'HYDERABAD'), ('Pune', 'PUNE'), ('Bang', 'BANG')], max_length=300)),
                ('date', models.DateTimeField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
