# Generated by Django 3.0 on 2019-12-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191212_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
                ('start_time', models.TimeField(max_length=100)),
                ('trainer_exp', models.CharField(max_length=50)),
            ],
        ),
    ]
